# Generated by Django 3.2.9 on 2021-11-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approved_by_admin',
            new_name='allow_by_admin',
        ),
    ]
