# Generated by Django 3.2.9 on 2021-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='image',
            field=models.ImageField(blank=True, upload_to='shop_images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='shop_images'),
        ),
    ]
