# Generated by Django 3.2.9 on 2021-11-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20211129_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='pin_code',
            field=models.CharField(default='452001', max_length=6),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_owner',
            field=models.ForeignKey(limit_choices_to={'role': 'shop'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
