# Generated by Django 3.2.9 on 2021-11-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211129_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
