# Generated by Django 3.2.9 on 2021-11-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
