# Generated by Django 3.2.9 on 2021-11-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='product_image')),
                ('purchase_price', models.PositiveIntegerField(blank=True)),
                ('sale_price', models.PositiveIntegerField(blank=True)),
                ('mfg_date', models.DateField(blank=True)),
                ('expiry_date', models.DateField(blank=True)),
                ('shop_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
