# Generated by Django 3.2.9 on 2021-12-01 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0010_product_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True)),
                ('unit_price', models.FloatField(blank=True)),
                ('subtotal', models.FloatField(blank=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('new', 'New'), ('ship', 'shipped'), ('delivered', 'delivered'), ('cancel', 'Cancel')], default='new', max_length=20)),
                ('order_date', models.DateTimeField(null=True)),
                ('customer_id', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orderlines', models.ManyToManyField(blank=True, to='order.SaleOrderLine')),
            ],
        ),
    ]
