# Generated by Django 3.2.9 on 2021-12-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='orderlines',
            new_name='orderline_ids',
        ),
    ]
